"""initial schema

Revision ID: cc53309ef86d
Revises: 
Create Date: 2025-10-03 03:55:27.950211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc53309ef86d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_path', sa.String(), nullable=False),
    sa.Column('video_subject', sa.String(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_histories_id'), 'video_histories', ['id'], unique=False)
    op.create_index(op.f('ix_video_histories_task_id'), 'video_histories', ['task_id'], unique=True)
    op.drop_index(op.f('ix_video_generation_history_id'), table_name='video_generation_history')
    op.drop_index(op.f('ix_video_generation_history_task_id'), table_name='video_generation_history')
    op.drop_table('video_generation_history')
    op.add_column('users', sa.Column('openai_api_key', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('pexels_api_keys', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('pixabay_api_keys', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pixabay_api_keys')
    op.drop_column('users', 'pexels_api_keys')
    op.drop_column('users', 'openai_api_key')
    op.create_table('video_generation_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('task_id', sa.VARCHAR(), nullable=True),
    sa.Column('video_subject', sa.VARCHAR(), nullable=True),
    sa.Column('video_script', sa.TEXT(), nullable=True),
    sa.Column('video_aspect', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('video_url', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_generation_history_task_id'), 'video_generation_history', ['task_id'], unique=1)
    op.create_index(op.f('ix_video_generation_history_id'), 'video_generation_history', ['id'], unique=False)
    op.drop_index(op.f('ix_video_histories_task_id'), table_name='video_histories')
    op.drop_index(op.f('ix_video_histories_id'), table_name='video_histories')
    op.drop_table('video_histories')
    # ### end Alembic commands ###
