"""add_payment_key_to_payments

Revision ID: dc29c046ce38
Revises: cc53309ef86d
Create Date: 2025-10-03 09:30:41.196929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc29c046ce38'
down_revision: Union[str, Sequence[str], None] = 'cc53309ef86d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_payments_payment_key'), 'payments', ['payment_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_payment_key'), table_name='payments')
    op.drop_column('payments', 'payment_key')
    # ### end Alembic commands ###
