"""add_auto_renew_fields_to_subscription

Revision ID: e3bf49be580b
Revises: 93bbca6dac25
Create Date: 2025-10-03 10:06:46.457669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3bf49be580b'
down_revision: Union[str, Sequence[str], None] = '93bbca6dac25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('auto_renew', sa.Integer(), nullable=True))
    op.add_column('subscriptions', sa.Column('billing_key', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('last_renewed_at', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('next_billing_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_subscriptions_billing_key'), 'subscriptions', ['billing_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_billing_key'), table_name='subscriptions')
    op.drop_column('subscriptions', 'next_billing_date')
    op.drop_column('subscriptions', 'last_renewed_at')
    op.drop_column('subscriptions', 'billing_key')
    op.drop_column('subscriptions', 'auto_renew')
    # ### end Alembic commands ###
